#!/usr/bin/env python
import argparse
import sys

import rospy

from object_pose_utils import MaskImageNode

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Mask an input image with another image", formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("image_topic", type=str, help="Input image topic (sensor_msg/Image")
    parser.add_argument("mask_topic", type=str, help="Mask topic (sensor_msg/Image)")
    parser.add_argument("-o", "--output", type=str, help="Output topic")
    parser.add_argument("--debug", action="store_true", help="Flag to produce debug output windows")

    args, unknown_args = parser.parse_known_args(sys.argv[1:])

    rospy.init_node("mask_image")
    mask_image_node = MaskImageNode(args.image_topic, args.mask_topic, output=args.output, debug=args.debug)

    while not rospy.is_shutdown():
        rospy.spin()
